version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    # volumes:
    #   - ./redis-data:/data
    # command: ["redis-server", "--appendonly", "yes"]
    restart: always 

  # server:
  #   image: glad47/sales-server:06
  #   container_name: server
  #   ports:
  #     - "8888:8888"
  #   restart: always 

  # app:
  #   image: glad47/sales-system:010
  #   container_name: app
  #   ports:
  #     - "3000:3000"
  #   restart: always  
